let employees = [{ "id": 1, "name": "Emlyn", "email": "edavidek0@nydailynews.com", "gender": "Male" },
{ "id": 2, "name": "Valeria", "email": "vepton1@usatoday.com", "gender": "Male" },
{ "id": 3, "name": "Homer", "email": "hdybald2@taobao.com", "gender": "Female" },
{ "id": 4, "name": "Benjie", "email": "bellul3@hp.com", "gender": "Female" },
{ "id": 5, "name": "Jacquenetta", "email": "jduthy4@amazon.de", "gender": "Male" },
{ "id": 6, "name": "Pete", "email": "praye5@slashdot.org", "gender": "Female" },
{ "id": 7, "name": "Derrik", "email": "dbrackpool6@arstechnica.com", "gender": "Female" },
{ "id": 8, "name": "Nathanial", "email": "nbeardow7@weather.com", "gender": "Female" },
{ "id": 9, "name": "Duane", "email": "djaskiewicz8@prlog.org", "gender": "Male" },
{ "id": 10, "name": "Joe", "email": "jarter9@webnode.com", "gender": "Male" },
{ "id": 11, "name": "Babs", "email": "btrucketta@ibm.com", "gender": "Female" },
{ "id": 12, "name": "Vilhelmina", "email": "vbumb@arstechnica.com", "gender": "Female" },
{ "id": 13, "name": "Rich", "email": "rbelonec@hp.com", "gender": "Female" },
{ "id": 14, "name": "Winslow", "email": "wedmondsond@toplist.cz", "gender": "Male" },
{ "id": 15, "name": "Corabella", "email": "cdimnagee@nifty.com", "gender": "Female" },
{ "id": 16, "name": "Charlton", "email": "cnowlandf@si.edu", "gender": "Female" },
{ "id": 17, "name": "Hernando", "email": "hblackdeng@wordpress.org", "gender": "Female" },
{ "id": 18, "name": "Ronald", "email": "rtregidgoh@bandcamp.com", "gender": "Genderfluid" },
{ "id": 19, "name": "Kile", "email": "krosenfruchti@auda.org.au", "gender": "Male" },
{ "id": 20, "name": "Cosimo", "email": "cburtj@hud.gov", "gender": "Female" },
{ "id": 21, "name": "Daveen", "email": "dconleyk@jugem.jp", "gender": "Male" },
{ "id": 22, "name": "Genna", "email": "gansteel@friendfeed.com", "gender": "Male" },
{ "id": 23, "name": "Lynn", "email": "lcarusm@addtoany.com", "gender": "Polygender" },
{ "id": 24, "name": "Adaline", "email": "amackilln@blogs.com", "gender": "Agender" },
{ "id": 25, "name": "Seumas", "email": "sheistermanno@purevolume.com", "gender": "Male" },
{ "id": 26, "name": "Johnny", "email": "jblomefieldp@blogtalkradio.com", "gender": "Male" },
{ "id": 27, "name": "Yettie", "email": "ygiocannoniq@mediafire.com", "gender": "Male" },
{ "id": 28, "name": "Vivianne", "email": "vthackhamr@pcworld.com", "gender": "Agender" },
{ "id": 29, "name": "Cami", "email": "cbares@altervista.org", "gender": "Male" },
{ "id": 30, "name": "Moll", "email": "mwarltont@miitbeian.gov.cn", "gender": "Male" },
{ "id": 31, "name": "Jonathan", "email": "jfloryu@goo.ne.jp", "gender": "Female" },
{ "id": 32, "name": "Creigh", "email": "csmithsonv@networkadvertising.org", "gender": "Male" },
{ "id": 33, "name": "Iolande", "email": "iourryw@dot.gov", "gender": "Female" },
{ "id": 34, "name": "Perren", "email": "plampittx@networksolutions.com", "gender": "Male" },
{ "id": 35, "name": "Denver", "email": "dalmeiday@de.vu", "gender": "Female" },
{ "id": 36, "name": "Pattin", "email": "phalleyz@360.cn", "gender": "Male" },
{ "id": 37, "name": "Erena", "email": "eheinish10@state.tx.us", "gender": "Female" },
{ "id": 38, "name": "Nowell", "email": "nsimonazzi11@soundcloud.com", "gender": "Female" },
{ "id": 39, "name": "Shawnee", "email": "slittleton12@google.com.au", "gender": "Male" },
{ "id": 40, "name": "Boote", "email": "bstrangward13@paypal.com", "gender": "Genderfluid" },
{ "id": 41, "name": "Nickie", "email": "nshimon14@hibu.com", "gender": "Female" },
{ "id": 42, "name": "Carlita", "email": "cthinn15@wordpress.com", "gender": "Male" },
{ "id": 43, "name": "Quint", "email": "qshelvey16@odnoklassniki.ru", "gender": "Male" },
{ "id": 44, "name": "Daphne", "email": "dstirman17@sina.com.cn", "gender": "Female" },
{ "id": 45, "name": "Kerrin", "email": "kdonavan18@cargocollective.com", "gender": "Female" },
{ "id": 46, "name": "Cal", "email": "cofaherty19@ucsd.edu", "gender": "Non-binary" },
{ "id": 47, "name": "Joela", "email": "jcroser1a@cisco.com", "gender": "Genderqueer" },
{ "id": 48, "name": "Darbie", "email": "ddeshon1b@wordpress.com", "gender": "Male" },
{ "id": 49, "name": "Ramsay", "email": "rdellabbate1c@example.com", "gender": "Female" },
{ "id": 50, "name": "Korrie", "email": "kdrewe1d@purevolume.com", "gender": "Male" },
{ "id": 51, "name": "Timotheus", "email": "thammerberg1e@jugem.jp", "gender": "Female" },
{ "id": 52, "name": "Lucas", "email": "lwaddicor1f@cdc.gov", "gender": "Female" },
{ "id": 53, "name": "Penrod", "email": "pthrelfall1g@webeden.co.uk", "gender": "Female" },
{ "id": 54, "name": "Sonnnie", "email": "sgeddis1h@miibeian.gov.cn", "gender": "Male" },
{ "id": 55, "name": "Sansone", "email": "skroin1i@tinypic.com", "gender": "Female" },
{ "id": 56, "name": "Madge", "email": "mgartery1j@hexun.com", "gender": "Male" },
{ "id": 57, "name": "Zachary", "email": "zmcbain1k@illinois.edu", "gender": "Female" },
{ "id": 58, "name": "Georgetta", "email": "godoran1l@paginegialle.it", "gender": "Male" },
{ "id": 59, "name": "Nowell", "email": "nlowdyane1m@google.co.jp", "gender": "Female" },
{ "id": 60, "name": "Lotti", "email": "lkeeler1n@devhub.com", "gender": "Male" },
{ "id": 61, "name": "Erhart", "email": "eharcourt1o@cam.ac.uk", "gender": "Male" },
{ "id": 62, "name": "Boniface", "email": "bbazire1p@bloglines.com", "gender": "Male" },
{ "id": 63, "name": "Hamish", "email": "hwoolsey1q@kickstarter.com", "gender": "Female" },
{ "id": 64, "name": "Brier", "email": "bbuzza1r@vinaora.com", "gender": "Male" },
{ "id": 65, "name": "Zebulon", "email": "zslad1s@ehow.com", "gender": "Female" },
{ "id": 66, "name": "Roselia", "email": "rotowey1t@usda.gov", "gender": "Male" },
{ "id": 67, "name": "Emily", "email": "ederisly1u@reuters.com", "gender": "Male" },
{ "id": 68, "name": "Gaile", "email": "gconnop1v@csmonitor.com", "gender": "Polygender" },
{ "id": 69, "name": "Myranda", "email": "mbohills1w@1688.com", "gender": "Male" },
{ "id": 70, "name": "Pattie", "email": "plidgate1x@ehow.com", "gender": "Male" },
{ "id": 71, "name": "Constanta", "email": "cbossel1y@boston.com", "gender": "Female" },
{ "id": 72, "name": "Dian", "email": "dcolville1z@blogger.com", "gender": "Male" },
{ "id": 73, "name": "Chickie", "email": "caltimas20@pcworld.com", "gender": "Female" },
{ "id": 74, "name": "Victoria", "email": "vgwillym21@hugedomains.com", "gender": "Female" },
{ "id": 75, "name": "Dolli", "email": "dharriss22@ovh.net", "gender": "Male" },
{ "id": 76, "name": "Jenda", "email": "jmeech23@senate.gov", "gender": "Female" },
{ "id": 77, "name": "Petronilla", "email": "pcracknall24@marriott.com", "gender": "Female" },
{ "id": 78, "name": "Melloney", "email": "mmoiser25@wunderground.com", "gender": "Male" },
{ "id": 79, "name": "Roanne", "email": "rcandwell26@hp.com", "gender": "Female" },
{ "id": 80, "name": "Janette", "email": "jpontin27@state.gov", "gender": "Female" },
{ "id": 81, "name": "Charline", "email": "cwerndly28@archive.org", "gender": "Male" },
{ "id": 82, "name": "Michal", "email": "moland29@bloomberg.com", "gender": "Female" },
{ "id": 83, "name": "Antonella", "email": "abromont2a@redcross.org", "gender": "Male" },
{ "id": 84, "name": "Oralee", "email": "ovanni2b@dion.ne.jp", "gender": "Female" },
{ "id": 85, "name": "Hewe", "email": "hashburner2c@wufoo.com", "gender": "Female" },
{ "id": 86, "name": "Clark", "email": "cfiridolfi2d@amazon.com", "gender": "Female" },
{ "id": 87, "name": "Holden", "email": "hdubarry2e@i2i.jp", "gender": "Male" },
{ "id": 88, "name": "Malchy", "email": "mgather2f@wufoo.com", "gender": "Female" },
{ "id": 89, "name": "Caitlin", "email": "cmaffioni2g@ted.com", "gender": "Female" },
{ "id": 90, "name": "Anica", "email": "abeharrell2h@rambler.ru", "gender": "Male" },
{ "id": 91, "name": "Nonna", "email": "nbeasleigh2i@miitbeian.gov.cn", "gender": "Male" },
{ "id": 92, "name": "Clark", "email": "ckidder2j@goo.gl", "gender": "Female" },
{ "id": 93, "name": "Cyrus", "email": "cmerali2k@about.com", "gender": "Male" },
{ "id": 94, "name": "Shae", "email": "slevens2l@bloglines.com", "gender": "Male" },
{ "id": 95, "name": "Gleda", "email": "gflacknell2m@php.net", "gender": "Male" },
{ "id": 96, "name": "Adel", "email": "aminerdo2n@xing.com", "gender": "Female" },
{ "id": 97, "name": "Blake", "email": "bizak2o@geocities.com", "gender": "Genderqueer" },
{ "id": 98, "name": "Miriam", "email": "mroston2p@instagram.com", "gender": "Male" },
{ "id": 99, "name": "Stanislas", "email": "sceland2q@blinklist.com", "gender": "Female" },
{ "id": 100, "name": "Shelly", "email": "sgenn2r@princeton.edu", "gender": "Bigender" }]

function getEmplyeeData() {
    let rows = ""
    employees.forEach((employee) => {
        rows = rows + `<tr>  
                        <td>  ${employee.id}</td>
                        <td>  ${employee.name}</td>
                        <td>  ${employee.email}</td>
                        <td>  ${employee.gender.toLocaleUpperCase()}</td>
                        </tr>`
    })
    document.getElementById("tbody-data").innerHTML = rows
}